# -*- coding: utf-8 -*-
"""logical regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJ1EBu4BJqZLeF6A7uV2G3b9nhxPMkSE
"""

# ===============================
# STEP 1: Upload Dataset
# ===============================
from google.colab import files
uploaded = files.upload()

# ===============================
# STEP 2: Import Libraries
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ===============================
# STEP 3: Load Dataset
# ===============================
df = pd.read_csv("cervical-cancer_csv.csv")

print("First 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

# ===============================
# STEP 4: Data Preprocessing
# ===============================

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values
df = df.fillna(df.mean(numeric_only=True))

# Convert categorical to numeric
df = pd.get_dummies(df, drop_first=True)

# ===============================
# STEP 5: Select Features & Target
# ===============================
# IMPORTANT: Target column is usually 'Biopsy'

target_column = "Biopsy"

X = df.drop(target_column, axis=1)
y = df[target_column]

# ===============================
# STEP 6: Train-Test Split
# ===============================
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===============================
# STEP 7: Apply Logistic Regression
# ===============================
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# ===============================
# STEP 8: Predictions
# ===============================
y_pred = model.predict(X_test)

# ===============================
# STEP 9: Evaluation
# ===============================
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ===============================
# STEP 10: Visualization
# ===============================
plt.figure()
plt.scatter(range(len(y_test)), y_test, label="Actual")
plt.scatter(range(len(y_pred)), y_pred, label="Predicted")
plt.legend()
plt.title("Actual vs Predicted")
plt.show()